version: "3.9"
services:
  cloudsec-app:
    build: .
    container_name: cloudsec-corp-app
    ports:
      - "5000:5000"
    env_file:
      - .env
    volumes:
      - ./.env:/app/.env:ro
      - ./data:/app/data:ro
      - ./logs:/app/logs
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
    restart: unless-stopped
